name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Add environment variables
        run: echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> $GITHUB_ENV
      # Optional build step
      - name: Build project
        run: |
          echo "No build script defined, skipping build."
          # Uncomment the next line if you have a build step
          # npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LeoDiscordMusicBot'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Log deployment status
        run: echo "Deployment completed successfully!"

      - name: Check node version
        run: node -v

      - name: Check npm version
        run: npm -v

      - name: List project files
        run: ls -al

      - name: Print environment variables
        run: printenv

   
